const AuthenticationActionTypes = {
  IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
  CREATE_REQUEST_TOKEN: "CREATE_REQUEST_TOKEN",
  CREATE_SESSION_WITH_LOGIN: "CREATE_SESSION_WITH_LOGIN",
  CREATE_SESSION: "CREATE_SESSION",
  DELETE_SESSION: "DELETE_SESSION",
};

export default AuthenticationActionTypes;
