const ConfigurationActionTypes = {
  LOAD_API_CONFIGURATIONS: "LOAD_API_CONFIGURATIONS",
  LOAD_COUNTRIES: "LOAD_COUNTRIES",
  LOAD_JOBS: "LOAD_JOBS",
  LOAD_LANGUAGES: "LOAD_LANGUAGES",
  LOAD_PRIMARY_TRANSLATIONS: "LOAD_PRIMARY_TRANSLATIONS",
  LOAD_TIME_ZONE: "LOAD_TIME_ZONE",
  LOAD_LANGUAGES_WITH_PRIMARY_TRANSLATIONS:
    "LOAD_LANGUAGES_WITH_PRIMARY_TRANSLATIONS",
  LOAD_DEFAULT_LANGUAGE: "LOAD_DEFAULT_LANGUAGE",
};

export default ConfigurationActionTypes;
