const MediaDetailPageActionTypes = {
  LOAD_MEDIA_DETAIL: "LOAD_MEDIA_DETAIL",
  LOAD_MEDIA_VIDEO: "LOAD_MEDIA_VIDEO",
  LOAD_MEDIA_DETAIL_AND_VIDEO_VIDEO: "LOAD_MEDIA_DETAIL_AND_VIDEO_VIDEO",
  LOAD_MEDIA_EXTERNAL_IDS: "LOAD_MEDIA_EXTERNAL_IDS",
  LOAD_MEDIA_WATCH_PROVIDER: "LOAD_MEDIA_WATCH_PROVIDER",
};

export default MediaDetailPageActionTypes;
