const MediaDetailPageActionTypes = {
  LOAD_MEDIA_DETAIL: "LOAD_MEDIA_DETAIL",
  LOAD_MEDIA_VIDEO: "LOAD_MEDIA_VIDEO",
  LOAD_MEDIA_EXTERNAL_IDS: "LOAD_MEDIA_EXTERNAL_IDS",
  LOAD_MEDIA_WATCH_PROVIDER: "LOAD_MEDIA_WATCH_PROVIDER",
  LOAD_MEDIA_CREDITS: "LOAD_MEDIA_CREDITS",
  LOAD_MEDIA_REVIEWS: "LOAD_MEDIA_REVIEWS",
  LOAD_TV_SEASON_EPISODE_LIST: "LOAD_TV_SEASON_EPISODE_LIST",
};

export default MediaDetailPageActionTypes;
