const TrendingActionTypes = {
  LOAD_TRENDING_ALL_DATA: "LOAD_TRENDING_ALL_DATA",
  LOAD_TRENDING_MOVIE_DATA: "LOAD_TRENDING_MOVIE_DATA",
  LOAD_TRENDING_TV_DATA: "LOAD_TRENDING_TV_DATA",
  LOAD_TRENDING_PERSON_DATA: "LOAD_TRENDING_PERSON_DATA",
  LOAD_TRENDING_MOVIE_TV_DATA: "LOAD_TRENDING_MOVIE_TV_DATA",
};

export default TrendingActionTypes;
